export const redWords = [
  //'3+',
  "4+",
  "5+",
  "6+",
  "7+",
  //'3 years',
  "4 years",
  "5 years",
  "6 years",
  "7 years",
  //'minimum 3',
  "minimum 4",
  "minimum 5",
  "minimum 6",
  "minimum 7",
  //'At least 3',
  "At least 4",
  "At least 5",
  "At least 6",
  "At least 7",
  //'Angular',
  //'vue',
  "wordpress",
  "Python",
  "full stack",
  "full-stack",
  "stack",
  "react native",
  "react-native",
  //"redux",
  "native",
  "salesforce",
  "Shopify",
  "C#",
  //"php",
  "Israel",
  "passport",
  "visa",
  "Must be Authorized to Work in United States without any sponsorship",
  "US Remote",
];
